serviceTree:
  landscape: &landscape entei
  cluster: &cluster onyx
tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster
clusterName: &clusterName entei-onyx
role: &role "arn:aws:iam::767398020544:role/entei-onyx-irsa-2024022112461446710000001a"
aws-ebs-csi-driver:
  enabled: true
  customLabels:
    !!merge <<: *tags
  storageClasses:
    - name: ebs-gp3
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      labels:
        !!merge <<: *tags
        tr8.io/layer: "1"
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
      parameters:
        type: gp3
        encrypted: "true"
  controller:
    replicaCount: 2
    podLabels:
      !!merge <<: *tags
    podAnnotations:
      !!merge <<: *tags
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: *role
    extraVolumeTags:
      !!merge <<: *tags
aws-efs-csi-driver:
  enabled: false
  storageClasses:
    - name: efs
      labels:
        !!merge <<: *tags
        tr8.io/layer: "1"
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
      parameters: {}
  replicaCount: 2
  controller:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: *role
    create: true
    podAnnotations:
      !!merge <<: *tags
aws-load-balancer-controller:
  enabled: true
  clusterName: *clusterName
  replicaCount: 2
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: *role
  additionalLabels:
    !!merge <<: *tags
  podLabels:
    !!merge <<: *tags
  podAnnotations:
    !!merge <<: *tags
zoneSpread:
  zones:
    zone1:
      zone: ap-southeast-1a
      enabled: true
      replicas: 1
    zone2:
      zone: ap-southeast-1b
      enabled: true
      replicas: 1
    zone3:
      zone: ap-southeast-1c
      enabled: true
      replicas: 1
