{{- range $k ,$v := .Values.zoneSpread.zones }}
{{- if $v.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sulfoxide-lead.fullname" $ }}-{{ $k }}
  labels: {{- include "sulfoxide-lead.labels" $ | nindent 4 }}
  annotations: {{- include "sulfoxide-lead.annotations" $ | nindent 4 }}
    atomi.cloud/module: "zone-spread"
spec:
  replicas: {{ $v.replicas}}
  selector:
    matchLabels: {{- include "sulfoxide-lead.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels: {{- include "sulfoxide-lead.selectorLabels" $ | nindent 8 }}
      annotations: {{- include "sulfoxide-lead.annotations" $ | nindent 8 }}
        atomi.cloud/module: "zone-spread"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause
          image: {{ $.Values.zoneSpread.config.image | default "public.ecr.aws/eks-distro/kubernetes/pause:3.7" }}
          resources: {{- toYaml $.Values.zoneSpread.config.resources | nindent 12 }}
          securityContext: {{- toYaml $.Values.zoneSpread.config.securityContext | nindent 12 }}
      nodeSelector:
        "topology.kubernetes.io/zone": {{ $v.zone }}
      securityContext: {{- toYaml $.Values.zoneSpread.config.podSecurityContext | nindent 8 }}
---
{{- end }}
{{- end }}